#!/usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use AfolabiAbass\App\TwitterCommand;
use Symfony\Component\Dotenv\Dotenv;

if (!in_array(PHP_SAPI, ['cli', 'phpdbg', 'embed'], true)) {
    echo 'Warning: The console should be invoked via the CLI version of PHP, not the '.PHP_SAPI.' SAPI'.PHP_EOL;
}

require_once __DIR__ . '/vendor/autoload.php';

if (!class_exists(Application::class) || !class_exists(Dotenv::class)) {
    throw new LogicException('You need to add "symfony/framework-bundle" and "symfony/dotenv" as Composer dependencies.');
}

$dotenv = new Dotenv();
$dotenv->load(__DIR__.'/.env');

define("TWITTER_CONSUMER_KEY", getenv('TWITTER_API_KEY'));
define("TWITTER_CONSUMER_SECRET", getenv('TWITTER_API_SECRET'));
define("OAUTH_TOKEN", getenv('TWITTER_ACCESS_TOKEN'));
define("OAUTH_SECRET", getenv('TWITTER_ACCESS_TOKEN_SECRET'));

$app = new Application();
$app->add(new TwitterCommand());
$app->run();
